package com.example.reminderbirthday_calendar.notification.common

const val EXTRA_MESSAGE_EVENT_NAME = "EXTRA_EVENT_MESSAGE"
const val EXTRA_ID_EVENT = "EXTRA_ID_EVENT"
const val EXTRA_NUMBER_NOTIFICATION = "EXTRA_NUMBER_NOTIFICATION"

const val EXTRA_DAY_NOTIFICATION = "EXTRA_DAY_NOTIFICATION"
const val EXTRA_MONTH_NOTIFICATION = "EXTRA_MONTH_NOTIFICATION"

const val EXTRA_HOUR_NOTIFICATION = "EXTRA_HOUR_NOTIFICATION"
const val EXTRA_MINUTE_NOTIFICATION = "EXTRA_MINUTE_NOTIFICATION"

const val NOTIFICATION_EVENT_CHANNEL_ID = "BIRTHDAY_REMINDER_EVENTS_ID"
const val NOTIFICATION_EVENT_CHANNEL_NAME = "Birthday Reminder Events"

const val NOTIFICATION_EVENT_ID = 1